### ISSUE TITLE
Cannot find module `request'

### ISSUE THREAD

**Issue by StockwerkOrange** [josephdadams/midi-relay#21]
Hi,
 i try to run the midi relay on my RPi3. Thats the Errormessage i get:

pi@raspberrypi:~/midi-relay-2.2.0 $ node main.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /home/pi/midi-relay-2.2.0/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/midi-relay-2.2.0/main.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/midi-relay-2.2.0/main.js' ]
}
pi@raspberrypi:~/midi-relay-2.2.0 $ 

Did i something wrong? Thanks for the help.

kind regards

**Comment by cjdenio** [comment]
Did you run `npm install` before running?

**Comment by StockwerkOrange** [comment]
Hi Caleb,

 thanks for the quick answer!
After installing like you said it runs perfectly fine. Thank you very much!!!
Maybe you can help me with this too:
I´ve try to trigger my Roland V-1HD connected to the Pi via USB (Midi) with the midi-relay module at companion. The remote control information about the V-1HD isnt very helpful to me. I like to change the Inputs 1-4 on A or B with the Bank Change but i dont know what i do have to fill in at the companion Button.
The V-1HD Device ID is 1, Midi Channel TX/RX is 1.

Thanks for your help

[V-1HD_RC_guide_eng02_W.pdf](https://github.com/josephdadams/midi-relay/files/6313104/V-1HD_RC_guide_eng02_W.pdf)

**Comment by StockwerkOrange** [comment]
Update: i found out that Input 1-4 on Channel A can changed with send Program Change Value 1-4. I try the other values to change Input 1-4 on Channel B but nothing happend...
