### ISSUE TITLE
Syntax issue on trigger

### ISSUE THREAD

**Issue by Arnault09** [josephdadams/midi-relay#28]
Hello,

I got this message when I start midi-relay

Triggers could not be loaded due to an error:
SyntaxError: Unexpected token m in JSON at position 2
    at JSON.parse (<anonymous>)
    at loadMIDITriggers (/snapshot/midi-relay/main.js:260:21)
    at /snapshot/midi-relay/main.js:360:3
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47

Here's my trigger 

{
midiport: 'USB MIDI Interface',
midicommand: 'noteon',
note: 40,
channel: 1,
velocity: 1,
actiontype: 'http',
url: 'http://127.0.0.1/JT_intro',
description: 'JT_intro'
}

Could you tell me where I'm wrong ?

Best regards,

**Comment by josephdadams** [comment]
Yes your key fields must be enclosed in quotes

‘“midiport”: “USB Midi Interface”`
