### ISSUE TITLE
Program crashes when refreshing the page on Brave

### ISSUE THREAD

**Issue by datadata95** [josephdadams/midi-relay#54]
**Describe the bug**
Crashes when refreshing the page.

**To Reproduce**
1. Start Midi Relay and open it's web config.
2. Web config turns out blank.
3. Refresh it and the triggers list comes up.
4. Refresh it again and the software crashes.

**Expected behavior**
The list of triggers would open immediately as web page is displayed.

**Screenshots**

<img width="272" alt="Skärmavbild 2024-02-06 kl  14 37 51" src="https://github.com/josephdadams/midi-relay/assets/69867381/a2c43743-5782-44bb-a105-153cbdcd1d45">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version 12.7.2

**Additional context**
Error log:

Unhandled Error
TypeError: Cannot read properties of undefined (reading 'id')
    at /Applications/midi-relay.app/Contents/Resources/app.asar/midi.js:965:9
    at Array.find (<anonymous>)
    at deleteTrigger (/Applications/midi-relay.app/Contents/Resources/app.asar/midi.js:964:11)
    at Object.deleteTrigger (/Applications/midi-relay.app/Contents/Resources/app.asar/midi.js:997:3)
    at Object.deleteTrigger (/Applications/midi-relay.app/Contents/Resources/app.asar/util.js:90:8)
    at Socket.<anonymous> (/Applications/midi-relay.app/Contents/Resources/app.asar/api.js:130:11)
    at Socket.emit (node:events:390:28)
    at Socket.emitUntyped (/Applications/midi-relay.app/Contents/Resources/app.asar/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Applications/midi-relay.app/Contents/Resources/app.asar/node_modules/socket.io/dist/socket.js:704:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by josephdadams** [comment]
Fix: don’t refresh the page. 

Jk.

I will see if I can fix that.

**Comment by datadata95** [comment]
> Fix: don’t refresh the page.
> 
> Jk.
> 
> I will see if I can fix that.

Thanks!

The problem is though, that it seems the application wont remember the configuration when started and displays the page empty, or the things are there but not seen. If I import the config it generates duplicates, which seem to be the way it should work.

Tried in Safari as well with the same result.

**Comment by josephdadams** [comment]
Can you send me your exported triggers? I am trying to recreate this issue and cannot.

**Comment by datadata95** [comment]
[midi-relay-triggers_2024_2_6.txt](https://github.com/josephdadams/midi-relay/files/14297856/midi-relay-triggers_2024_2_6.txt)

[midi-relay-triggers_2024_2_15.txt](https://github.com/josephdadams/midi-relay/files/14297902/midi-relay-triggers_2024_2_15.txt)


I'm currently on Companion 3.2.1
